### ISSUE TITLE
KeyError When Accessing '1d' in Dictionary During Checkpoint Loading for NNSK Training

### ISSUE THREAD

**Issue by T-S-Liang** [deepmodeling/DeePTB#138]
### Describe the bug

Traceback (most recent call last):
  File "/home/usr/anaconda3/envs/dptb-gpu/bin/dptb", line 8, in <module>
    sys.exit(main())
  File "/home/usr/anaconda3/envs/dptb-gpu/lib/python3.9/site-packages/dptb/entrypoints/main.py", line 401, in main
    train(**dict_args)
  File "/home/usr/anaconda3/envs/dptb-gpu/lib/python3.9/site-packages/dptb/entrypoints/train.py", line 186, in train
    model = build_model(checkpoint=checkpoint, model_options=jdata["model_options"], common_options=jdata["common_options"], statistics=train_datasets.E3statistics())
  File "/home/usr/anaconda3/envs/dptb-gpu/lib/python3.9/site-packages/dptb/nn/build.py", line 172, in build_model
    model = NNSK.from_reference(checkpoint, **model_options["nnsk"], **common_options)
  File "/home/usr/anaconda3/envs/dptb-gpu/lib/python3.9/site-packages/dptb/nn/nnsk.py", line 531, in from_reference
    riorb, rjorb = ref_idp.full_basis_to_basis[iasym][rfiorb], ref_idp.full_basis_to_basis[jasym][rfjorb]
KeyError: '1d'

### Expected behavior

Greetings,

I encountered an issue while loading a checkpoint for NNSK training and need some assistance. The problem involves a KeyError when accessing '1d' in a dictionary, which seems to halt the process. I have attached the relevant files and a detailed error log to help reproduce the bug.

Thank you very much for your time and support! Please let me know if there's any more information I can provide or steps I should try.

### To Reproduce

[ISSUE_01_Basis.zip](https://github.com/deepmodeling/DeePTB/files/15057730/ISSUE_01_Basis.zip)

**Comment by floatingCatty** [comment]
@T-S-Liang 
Hello!

Thank you very much for the feedback, we have just fix this bug. Please pull the latest main branch to update your code.
